FROM gzserver:latest

# This image extends from official gzserver image to add a
# gazebo user and automatically download gazebo models.

ARG USERID=1000

# setup environment
ENV DEBIAN_FRONTEND noninteractive
ENV LANG en_US.UTF-8

# Install bootstrap tools
#     sudo \
RUN apt-get update && apt-get install --no-install-recommends -y --allow-unauthenticated \
    bash-completion \
    git \
    wget \
    locales \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a new user called ariac. Note: we don't add them to the sudo group
ENV USERNAME ariac
RUN locale-gen en_US.UTF-8
RUN adduser -u $USERID --gecos "Development User" --disabled-password $USERNAME
RUN echo "export QT_X11_NO_MITSHM=1" >> /home/$USERNAME/.bashrc

USER $USERNAME
WORKDIR /home/$USERNAME

# Get gazebo models by calling wget here
# Do it early since it's big
RUN git clone https://github.com/osrf/gazebo_models $HOME/.gazebo/models
